apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-dob13-wordpress
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi